default_config:

mqtt:
  fan: !include_dir_merge_list fan/
  select: !include_dir_merge_list select/
  sensor: !include_dir_merge_list sensor/
  switch: !include_dir_merge_list switch/
media_player: !include_dir_merge_list media_player/